
import java.sql.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class receipt extends javax.swing.JFrame {

    /**
     * Creates new form receipt
     */
    public receipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMonthChooser1 = new CalendarBean.JMonthChooser();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTF1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTF2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTF3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTF5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTF4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTF6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTF7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CB1 = new javax.swing.JComboBox();
        CB2 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        y1 = new CalendarBean.JYearChooser();
        m1 = new CalendarBean.JMonthChooser();
        d1 = new CalendarBean.JDayChooser();
        jLabel14 = new javax.swing.JLabel();
        y2 = new CalendarBean.JYearChooser();
        m2 = new CalendarBean.JMonthChooser();
        d2 = new CalendarBean.JDayChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jTF8 = new javax.swing.JTextField();
        jTF9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        CB3 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CB4 = new javax.swing.JComboBox();
        jTF10 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jCB4 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\pictures\\OOTP_beach-villa.jpg")); // NOI18N

        jLabel20.setText("jLabel20");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("BOOKING NO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        getContentPane().add(jTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 264, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 264, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 59, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("CONTACT NUMBER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        getContentPane().add(jTF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 264, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("NO. OF DAYS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));
        getContentPane().add(jTF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 264, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("ROOM NO.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));
        getContentPane().add(jTF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 264, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("CHARGES PER DAY");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));
        getContentPane().add(jTF6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 264, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("TOTAL AMOUNT");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));
        getContentPane().add(jTF7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 264, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel9.setText("BOOKING DETAILS :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 330, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 0, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 102));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 90, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("ROOM TYPE");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("BED TYPE");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, -1, -1));

        CB1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "NON-AC" }));
        getContentPane().add(CB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 110, -1));

        CB2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SINGLE", "DOUBLE", "DELUXE" }));
        getContentPane().add(CB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 110, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("CHECK IN");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, -1, -1));
        getContentPane().add(y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, -1, -1));
        getContentPane().add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, -1, -1));
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("CHECK OUT");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, -1, -1));
        getContentPane().add(y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 500, -1, -1));
        getContentPane().add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 490, -1, -1));
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, -1, -1));

        jt.setBackground(new java.awt.Color(204, 204, 204));
        jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ROOM TYPE", "BED TYPE", "CHECK IN", "CHECK OUT"
            }
        ));
        jScrollPane1.setViewportView(jt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 520, 90));

        jButton3.setBackground(new java.awt.Color(204, 255, 102));
        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton3.setText("CONFIRM STATUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 200, 30));
        getContentPane().add(jTF8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 170, -1));
        getContentPane().add(jTF9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 170, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 102));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, -1, -1));

        jButton4.setBackground(new java.awt.Color(204, 255, 102));
        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton4.setText("PROCEED &  PAY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 190, -1));

        jButton5.setBackground(new java.awt.Color(204, 255, 102));
        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton5.setText("CLEAR TEXT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 690, 150, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("CVV ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        CB3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "USE LATER" }));
        getContentPane().add(CB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 120, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("ADDRESS");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("CUSTOMER ID");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        CB4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AADHAR", "VOTER ID", "PAN " }));
        getContentPane().add(CB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 260, -1));
        getContentPane().add(jTF10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 260, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("CARD NUMBER");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jCB4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "USE LATER" }));
        getContentPane().add(jCB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 120, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\pictures\\OOTP_beach-villa.jpg")); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1150, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new welcomepage().setVisible(true);   
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 DefaultTableModel model=(DefaultTableModel)jt.getModel();
int a,b,c,a1,b1,c1;
a=y1.getYear();
b=m1.getMonth()+1;
c=d1.getDay();
jTF8.setText(+a+"-"+b+"-"+c);
a1=y2.getYear();
b1=m2.getMonth()+1;
c1=d2.getDay();
jTF9.setText(+a1+"-"+b1+"-"+c1);
model.addRow(new Object[]{CB1.getSelectedItem(),CB2.getSelectedItem(), jTF8.getText(),jTF9.getText()});
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{
    Class.forName("java.sql.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/rishita","root","opjs");
    
        int g,k=0;
        String roomtype,bedtype;
        roomtype=CB1.getSelectedItem().toString();
        bedtype=CB2.getSelectedItem().toString();
        if(roomtype.equals("AC")&& bedtype.equals("SINGLE")){
            k=3000;
        }else if(roomtype.equals("NON-AC") && bedtype.equals("SINGLE")){
            k=2000;
        }else if(roomtype.equals("NON-AC") && bedtype.equals("DOUBLE")){
            k=3500;
        } else if(roomtype.equals("AC") && bedtype.equals("DOUBLE")){
            k=4000;
        }else if(roomtype.equals("AC") && bedtype.equals("DELUXE")){
            k=6000;
        }else if(roomtype.equals("NON-AC") && bedtype.equals("DELUXE")){
            k=5000;
        }       jTF6.setText(""+k);
        int a=Integer.parseInt(jTF1.getText());
        String b=jTF2.getText();
        long c;
    c = Long.parseLong(jTF3.getText());
    
        int d=Integer.parseInt(jTF4.getText());
        int days;
        int e,f;
        e=d1.getDay();
        f=d2.getDay();
        days=f-e;
        jTF5.setText(""+days);
        jTF6.setText(""+k);
        int h=Integer.parseInt(jTF5.getText());
        g=k*h;
        jTF7.setText(""+g);
        String i;
        i=CB3.getSelectedItem().toString();
        String j=jTF10.getText();
        String l=CB4.getSelectedItem().toString();
        String m=jCB4.getSelectedItem().toString();
        
        

        String q="insert into imperial values("+"\""+a+"\",'"+b+"',"+"\""+c+"\","+"\""+d+"\","+"\""+h+"\","+"\""+k+"\","+"\""+g+"\","+"\""+roomtype+"\","+"\""+bedtype+"\","+"\""+i+"\","+"\""+j+"\","+"\""+l+"\","+"\""+m+"\");";
Statement stmt=con.createStatement();
stmt.executeUpdate(q);
      
            JOptionPane.showMessageDialog(null,"BOOKING CONFIRMED SUCCESSFULLY");
            new paymentmode().setVisible(true);
            this.setVisible(false);
            stmt.close();
            con.close();
        }



catch(Exception e){
    JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new usernamepwd().setVisible(true);   
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
jTF1.setText("");
jTF2.setText("");
jTF3.setText("");
jTF4.setText("");
jTF5.setText("");
jTF6.setText("");
jTF7.setText("");
jTF8.setText("");
jTF9.setText("");
DefaultTableModel model=(DefaultTableModel) jt.getModel();
model.setRowCount(0);// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CB1;
    private javax.swing.JComboBox CB2;
    private javax.swing.JComboBox CB3;
    private javax.swing.JComboBox CB4;
    private CalendarBean.JDayChooser d1;
    private CalendarBean.JDayChooser d2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jCB4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private CalendarBean.JMonthChooser jMonthChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF1;
    private javax.swing.JTextField jTF10;
    private javax.swing.JTextField jTF2;
    private javax.swing.JTextField jTF3;
    private javax.swing.JTextField jTF4;
    private javax.swing.JTextField jTF5;
    private javax.swing.JTextField jTF6;
    private javax.swing.JTextField jTF7;
    private javax.swing.JTextField jTF8;
    private javax.swing.JTextField jTF9;
    private javax.swing.JTable jt;
    private CalendarBean.JMonthChooser m1;
    private CalendarBean.JMonthChooser m2;
    private CalendarBean.JYearChooser y1;
    private CalendarBean.JYearChooser y2;
    // End of variables declaration//GEN-END:variables

    private static class Days {

        private static Object daysBetween(int e, int f) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public Days() {
        }
    }
}
